const NEWS_ACTION_TYPES = {
  FETCH_NEWS_HEADLINES: "FETCH_NEWS_HEADLINES",
  FETCH_NEWS_HEADLINES_FAIL: "FETCH_NEWS_HEADLINES_FAIL",
  FETCH_NEWS_HEADLINES_SUCCESS: "FETCH_NEWS_HEADLINES_SUCCESS"
};

export default NEWS_ACTION_TYPES;
