const NEWS_ACTION_TYPES = {
  START_INITIAL_PRODUCTS_FETCH: "START_INITIAL_PRODUCTS_FETCH",
  START_INITIAL_FETCH_PRODUCTS_BY_CATEGORY: "START_INITIAL_FETCH_PRODUCTS_BY_CATEGORY",
  INITIAL_PRODUCTS_FETCH_FAIL: "INITIAL_PRODUCTS_FETCH_FAIL",
  INITIAL_PRODUCTS_FETCH_SUCCESS: "INITIAL_PRODUCTS_FETCH_SUCCESS",
  START_LOADING_MORE_PRODUCTS: "START_LOADING_MORE_PRODUCTS",
  START_LOADING_MORE_PRODUCTS_BY_CATEGORY: "START_LOADING_MORE_PRODUCTS_BY_CATEGORY",
  LOADING_MORE_PRODUCTS_FAIL: "LOADING_MORE_PRODUCTS_FAIL",
  LOADING_MORE_PRODUCTS_SUCCESS: "LOADING_MORE_PRODUCTS_SUCCESS",
  NO_MORE_PRODUCTS_TO_LOAD: "NO_MORE_PRODUCTS_TO_LOAD",
  FETCH_PRODUCT_BY_ID: "FETCH_PRODUCT_BY_ID",
  FETCH_PRODUCT_BY_ID_FAIL: "FETCH_PRODUCT_BY_ID_FAIL",
  FETCH_PRODUCT_BY_ID_SUCCESS: "FETCH_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID: "DELETE_PRODUCT_BY_ID",
  DELETE_PRODUCT_BY_ID_FAIL: "DELETE_PRODUCT_BY_ID_FAIL",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  CREATE_NEW_PRODUCT: "CREATE_NEW_PRODUCT",
  CREATE_NEW_PRODUCT_FAIL: "CREATE_NEW_PRODUCT_FAIL",
  CREATE_NEW_PRODUCT_SUCCESS: "CREATE_NEW_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_BY_ID: "UPDATE_PRODUCT_BY_ID",
  UPDATE_PRODUCT_BY_ID_FAIL: "UPDATE_PRODUCT_BY_ID_FAIL",
  UPDATE_PRODUCT_BY_ID_SUCCESS: "UPDATE_PRODUCT_BY_ID_SUCCESS"
};

export default NEWS_ACTION_TYPES;
